name: Build frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate To Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_type: access_token
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        access_token_lifetime: 300s

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
        cache-dependency-path: frontend/pnpm-lock.yaml
        node-version: 18.x

    - name: Install dependencies
      working-directory: frontend/
      run: pnpm i --frozen-lockfile

    - name: Build
      working-directory: frontend/
      run: pnpx vite build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: frontend-data
        path: frontend/dist
